## 1. Import Required Libraries

In [2]:
# Data Handling
import pandas as pd
import numpy as np
!pip install scikit-learn

# Dataset
from sklearn.datasets import load_breast_cancer

# Data Split
from sklearn.model_selection import train_test_split

# Machine Learning Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

# Evaluation Metrics
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    confusion_matrix,
    classification_report
)

# Save Models
import joblib

print("All libraries imported successfully")

Requirement already satisfied: scikit-learn in /home/cloud/anaconda3/lib/python3.12/site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in /home/cloud/anaconda3/lib/python3.12/site-packages (from scikit-learn) (2.5.2)
Requirement already satisfied: scipy>=1.10.0 in /home/cloud/anaconda3/lib/python3.12/site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in /home/cloud/anaconda3/lib/python3.12/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: narwhals>=2.0.1 in /home/cloud/anaconda3/lib/python3.12/site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /home/cloud/anaconda3/lib/python3.12/site-packages (from scikit-learn) (3.6.0)
All libraries imported successfully

## 2.Load the Breast Cancer Wisconsin Dataset
### We have the Breast Cancer Wisconsin dataset loaded into a DataFrame. This dataset contains 569 records and 30 features, satisfying the assignment requirements

In [7]:
# Load Breast Cancer Wisconsin Dataset

data = load_breast_cancer()

# Create DataFrame
df = pd.DataFrame(data.data, columns=data.feature_names)

# Add Target Column
df["target"] = data.target

# Display dataset information
print("Dataset Shape:", df.shape)
print("\nTarget Values:")
print(df["target"].value_counts())

# Display first 5 records
df.head()

Dataset Shape: (569, 31)

Target Values:
target
1    357
0    212
Name: count, dtype: int64

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

## 3.Split Dataset into Features, Target, Training Data and Test Data
### we must divide the dataset into:
Training Data (80%) → Used to train the ML models.  
Testing Data (20%) → Used to calculate Accuracy, AUC, Precision, Recall, F1, and MCC metrics

In [11]:
# Features (X) and Target (y)

X = df.drop("target", axis=1)
y = df["target"]

# Split data into Training and Testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

Training Data Shape: (455, 30)
Testing Data Shape: (114, 30)

## 4.Train Logistic Regression Model

In [14]:
# Logistic Regression Model

lr_model = LogisticRegression(max_iter=10000)

# Train the model
lr_model.fit(X_train, y_train)

print("Logistic Regression model trained successfully")

Logistic Regression model trained successfully

## 5.Calculate All Required Metrics for Logistic Regression
### The assignment requires these metrics for every model:
Accuracy  
AUC Score    
Precision   
Recall  
F1 Score   
MCC Score

In [18]:
# Make Predictions

y_pred = lr_model.predict(X_test)

# Probability predictions (needed for AUC)
y_prob = lr_model.predict_proba(X_test)[:, 1]

# Calculate Metrics

accuracy = accuracy_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_prob)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
mcc = matthews_corrcoef(y_test, y_pred)

# Display Results

print("Logistic Regression Results")
print("-" * 40)
print("Accuracy :", round(accuracy, 4))
print("AUC      :", round(auc, 4))
print("Precision:", round(precision, 4))
print("Recall   :", round(recall, 4))
print("F1 Score :", round(f1, 4))
print("MCC Score:", round(mcc, 4))

Logistic Regression Results
----------------------------------------
Accuracy : 0.9649
AUC      : 0.9954
Precision: 0.9595
Recall   : 0.9861
F1 Score : 0.9726
MCC Score: 0.9245

## 6.Save the Logistic Regression Model

In [21]:
# Save Logistic Regression Model

joblib.dump(lr_model, "logistic_regression.pkl")

print("Model saved successfully")

Model saved successfully

## 7.Train the Decision Tree Classifier

In [32]:
# Decision Tree Classifier

dt_model = DecisionTreeClassifier(
    random_state=42
)

# Train the model
dt_model.fit(X_train, y_train)

print("Decision Tree model trained successfully")

Decision Tree model trained successfully

## 8.Calculate All Required Metrics for Decision Tree
### The assignment requires these metrics for every model:
Accuracy  
AUC Score  
Precision  
Recall  
F1 Score  
MCC Score

In [34]:
# Decision Tree Predictions

dt_pred = dt_model.predict(X_test)

# Probability predictions for AUC
dt_prob = dt_model.predict_proba(X_test)[:, 1]

# Metrics

dt_accuracy = accuracy_score(y_test, dt_pred)
dt_auc = roc_auc_score(y_test, dt_prob)
dt_precision = precision_score(y_test, dt_pred)
dt_recall = recall_score(y_test, dt_pred)
dt_f1 = f1_score(y_test, dt_pred)
dt_mcc = matthews_corrcoef(y_test, dt_pred)

# Display Results

print("Decision Tree Results")
print("-" * 40)
print("Accuracy :", round(dt_accuracy, 4))
print("AUC      :", round(dt_auc, 4))
print("Precision:", round(dt_precision, 4))
print("Recall   :", round(dt_recall, 4))
print("F1 Score :", round(dt_f1, 4))
print("MCC Score:", round(dt_mcc, 4))

Decision Tree Results
----------------------------------------
Accuracy : 0.9123
AUC      : 0.9157
Precision: 0.9559
Recall   : 0.9028
F1 Score : 0.9286
MCC Score: 0.8174

## 9.Save the Decision Tree Model

In [37]:
# Save Decision Tree Model

joblib.dump(dt_model, "decision_tree.pkl")

print("Decision Tree model saved successfully")

Decision Tree model saved successfully

## 10.Train the k-Nearest Neighbors (kNN) Model
train the third mandatory model, kNN (K-Nearest Neighbor Classifier)

In [42]:
# K-Nearest Neighbor (kNN) Model

knn_model = KNeighborsClassifier(n_neighbors=5)

# Train the model
knn_model.fit(X_train, y_train)

print("kNN model trained successfully")

kNN model trained successfully

## 11.Calculate All Required Metrics for kNN
### The assignment requires these metrics for every model:
Accuracy  
AUC Score  
Precision  
Recall  
F1 Score  
MCC Score

In [45]:
# kNN Predictions

knn_pred = knn_model.predict(X_test)

# Probability predictions for AUC
knn_prob = knn_model.predict_proba(X_test)[:, 1]

# Metrics

knn_accuracy = accuracy_score(y_test, knn_pred)
knn_auc = roc_auc_score(y_test, knn_prob)
knn_precision = precision_score(y_test, knn_pred)
knn_recall = recall_score(y_test, knn_pred)
knn_f1 = f1_score(y_test, knn_pred)
knn_mcc = matthews_corrcoef(y_test, knn_pred)

# Display Results

print("kNN Results")
print("-" * 40)
print("Accuracy :", round(knn_accuracy, 4))
print("AUC      :", round(knn_auc, 4))
print("Precision:", round(knn_precision, 4))
print("Recall   :", round(knn_recall, 4))
print("F1 Score :", round(knn_f1, 4))
print("MCC Score:", round(knn_mcc, 4))

kNN Results
----------------------------------------
Accuracy : 0.9123
AUC      : 0.9559
Precision: 0.9429
Recall   : 0.9167
F1 Score : 0.9296
MCC Score: 0.8139

## 12.Save the kNN Model

In [48]:
# Save kNN Model

joblib.dump(knn_model, "knn_model.pkl")

print("kNN model saved successfully")

kNN model saved successfully

## 13.Train the Naive Bayes Model
For the Breast Cancer Wisconsin dataset, Gaussian Naive Bayes is appropriate because the features are continuous numeric values.

In [51]:
# Gaussian Naive Bayes Model

nb_model = GaussianNB()

# Train the model
nb_model.fit(X_train, y_train)

print("Naive Bayes model trained successfully")

Naive Bayes model trained successfully

## 14.Calculate All Required Metrics for Naive Bayes
The assignment requires these metrics for every model:
Accuracy  
AUC Score  
Precision  
Recall  
F1 Score  
MCC Score

In [54]:
# Naive Bayes Predictions

nb_pred = nb_model.predict(X_test)

# Probability predictions for AUC
nb_prob = nb_model.predict_proba(X_test)[:, 1]

# Metrics

nb_accuracy = accuracy_score(y_test, nb_pred)
nb_auc = roc_auc_score(y_test, nb_prob)
nb_precision = precision_score(y_test, nb_pred)
nb_recall = recall_score(y_test, nb_pred)
nb_f1 = f1_score(y_test, nb_pred)
nb_mcc = matthews_corrcoef(y_test, nb_pred)

# Display Results

print("Naive Bayes Results")
print("-" * 40)
print("Accuracy :", round(nb_accuracy, 4))
print("AUC      :", round(nb_auc, 4))
print("Precision:", round(nb_precision, 4))
print("Recall   :", round(nb_recall, 4))
print("F1 Score :", round(nb_f1, 4))
print("MCC Score:", round(nb_mcc, 4))

Naive Bayes Results
----------------------------------------
Accuracy : 0.9386
AUC      : 0.9878
Precision: 0.9452
Recall   : 0.9583
F1 Score : 0.9517
MCC Score: 0.8676

## 15.Save the Naive Bayes Model

In [57]:
# Save Naive Bayes Model

joblib.dump(nb_model, "naive_bayes.pkl")

print("Naive Bayes model saved successfully")

Naive Bayes model saved successfully

## 16.Train the Random Forest Model

In [60]:
# Random Forest Model

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train the model
rf_model.fit(X_train, y_train)

print("Random Forest model trained successfully")

Random Forest model trained successfully

## 17.Calculate All Required Metrics for Random Forest
The assignment requires these metrics for every model:
Accuracy  
AUC Score  
Precision  
Recall  
F1 Score  
MCC Score

In [63]:
# Random Forest Predictions

rf_pred = rf_model.predict(X_test)

# Probability predictions for AUC
rf_prob = rf_model.predict_proba(X_test)[:, 1]

# Metrics

rf_accuracy = accuracy_score(y_test, rf_pred)
rf_auc = roc_auc_score(y_test, rf_prob)
rf_precision = precision_score(y_test, rf_pred)
rf_recall = recall_score(y_test, rf_pred)
rf_f1 = f1_score(y_test, rf_pred)
rf_mcc = matthews_corrcoef(y_test, rf_pred)

# Display Results

print("Random Forest Results")
print("-" * 40)
print("Accuracy :", round(rf_accuracy, 4))
print("AUC      :", round(rf_auc, 4))
print("Precision:", round(rf_precision, 4))
print("Recall   :", round(rf_recall, 4))
print("F1 Score :", round(rf_f1, 4))
print("MCC Score:", round(rf_mcc, 4))

Random Forest Results
----------------------------------------
Accuracy : 0.9561
AUC      : 0.9937
Precision: 0.9589
Recall   : 0.9722
F1 Score : 0.9655
MCC Score: 0.9054

## 18.Save the Random Forest Model

In [66]:
# Save Random Forest Model

joblib.dump(rf_model, "random_forest.pkl")

print("Random Forest model saved successfully")

Random Forest model saved successfully

## 19.Create the Final Comparison Table

In [69]:
# Create Final Comparison Table

results_df = pd.DataFrame({
    "ML Model Name": [
        "Logistic Regression",
        "Decision Tree",
        "kNN",
        "Naive Bayes",
        "Random Forest"
    ],
    "Accuracy": [
        accuracy,
        dt_accuracy,
        knn_accuracy,
        nb_accuracy,
        rf_accuracy
    ],
    "AUC": [
        auc,
        dt_auc,
        knn_auc,
        nb_auc,
        rf_auc
    ],
    "Precision": [
        precision,
        dt_precision,
        knn_precision,
        nb_precision,
        rf_precision
    ],
    "Recall": [
        recall,
        dt_recall,
        knn_recall,
        nb_recall,
        rf_recall
    ],
    "F1": [
        f1,
        dt_f1,
        knn_f1,
        nb_f1,
        rf_f1
    ],
    "MCC": [
        mcc,
        dt_mcc,
        knn_mcc,
        nb_mcc,
        rf_mcc
    ]
})

results_df = results_df.round(4)

results_df

         ML Model Name  Accuracy     AUC  Precision  Recall      F1     MCC
0  Logistic Regression    0.9649  0.9954     0.9595  0.9861  0.9726  0.9245
1        Decision Tree    0.9123  0.9157     0.9559  0.9028  0.9286  0.8174
2                  kNN    0.9123  0.9559     0.9429  0.9167  0.9296  0.8139
3          Naive Bayes    0.9386  0.9878     0.9452  0.9583  0.9517  0.8676
4        Random Forest    0.9561  0.9937     0.9589  0.9722  0.9655  0.9054

## 20.Create test_data.csv

In [72]:
# Save Test Dataset for Streamlit App

test_data = X_test.copy()

test_data.to_csv("../test_data.csv", index=False)

print("test_data.csv created successfully")
print("Rows:", len(test_data))
print("Columns:", len(test_data.columns))

test_data.csv created successfully
Rows: 114
Columns: 30

In [74]:
import os
print(os.path.exists("../test_data.csv"))

True

## 21.Generate a Classification Report for Logistic Regression

In [77]:
# Classification Report - Logistic Regression

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.93      0.95        42
           1       0.96      0.99      0.97        72

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

## 22.Verify Your Final Comparison Table and Identify the Winner

In [80]:
# Sort Models by Accuracy

results_df.sort_values(
    by="Accuracy",
    ascending=False
)

         ML Model Name  Accuracy     AUC  Precision  Recall      F1     MCC
0  Logistic Regression    0.9649  0.9954     0.9595  0.9861  0.9726  0.9245
4        Random Forest    0.9561  0.9937     0.9589  0.9722  0.9655  0.9054
3          Naive Bayes    0.9386  0.9878     0.9452  0.9583  0.9517  0.8676
2                  kNN    0.9123  0.9559     0.9429  0.9167  0.9296  0.8139
1        Decision Tree    0.9123  0.9157     0.9559  0.9028  0.9286  0.8174

## 23.Save the Comparison Table to a CSV File

In [83]:
# Save Model Comparison Results

results_df.to_csv(
    "../model_comparison_results.csv",
    index=False
)

print("Model comparison results saved successfully")

Model comparison results saved successfully